### ISSUE TITLE
How do you send mail to this?

### ISSUE THREAD

**Issue by HotMonkeyWings** [soveran/mt.c#1]
Sorry if it is a newbie question, I'm just wondering how we can send mails to the server once we run it

**Comment by soveran** [comment]
Hey! It's a good question. When running mailcat you get an SMTP server running in the port you configure (by default, port 25). Then you can send emails using that port and localhost as if it were a regular SMTP server. But I would like to give you something more concrete, like a working example. Can you tell me which programming language you are using and with which mailing library?

**Comment by HotMonkeyWings** [comment]
Hey I'm really sorry for the later reply, but I was doing a project on making an SMTP server at the time. I was using C for the implementation. Thanks for offering the help, much appreciated!
